### ISSUE TITLE
Fairseq error

### ISSUE THREAD

**Issue by SmoothBrainApe** [daswer123/rvc-python#15]
I encountered another error when using infer_file. Seems to be fairseq issue.

```
Traceback (most recent call last):
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/test_rvc.py", line 1, in <module>
    from rvc_python.infer import infer_file
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/rvc_python/__init__.py", line 1, in <module>
    import rvc_python.infer
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/rvc_python/infer.py", line 2, in <module>
    from rvc_python.modules.vc.modules import VC
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/rvc_python/modules/vc/modules.py", line 19, in <module>
    from rvc_python.modules.vc.utils import *
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/rvc_python/modules/vc/utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/chupz22/Desktop/Desktop_Files/Programs/VSCodiumProjects/ChatBot/venv/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
```

**Comment by SmoothBrainApe** [comment]
Sorted. Python version should be <3.11. I resintalled python 3.10 and now it is working. 3.11 onwards will not work. Thanks
