### ISSUE TITLE
Model {model_name} not found

### ISSUE THREAD

**Issue by Dartvauder** [daswer123/rvc-python#24]
Hello friend. I really wanted to add RVC technology to my project and I'm glad I found your repository. But it gives me errors.

When I use the method through the python module, I get this error 

is_half:True, device:cuda
2024-09-03 20:56:50 | INFO | rvc_python.configs.config | Found GPU NVIDIA GeForce RTX 4070
Traceback (most recent call last):
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Coding\Python\NeuroSandboxWebUI\LaunchFiles\appEN.py", line 5979, in process_rvc
    rvc.load_model(model_file)
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\rvc_python\infer.py", line 59, in load_model
    raise ValueError(f"Model {model_name} not found.")
ValueError: Model inputs\audio\rvc_models\oxxxymiron\Oxxxymiron.pth not found. 

When I use the method through the Command Line Interface, then this

2024-09-03 20:38:28 | INFO | rvc_python.configs.config | Found GPU NVIDIA GeForce RTX 4070
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "C:\Users\dartv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dartv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\rvc_python\__main__.py", line 91, in <module>
    main()
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\rvc_python\__main__.py", line 57, in main
    rvc.load_model(args.model)
  File "C:\Coding\Python\NeuroSandboxWebUI\venv\lib\site-packages\rvc_python\infer.py", line 59, in load_model
    raise ValueError(f"Model {model_name} not found.")
ValueError: Model inputs/audio/rvc_models/oxxxymiron/Oxxxymiron.pth not found.

My code for python module method:

def process_rvc(input_audio, model_folder, f0method, f0up_key, index_rate, filter_radius, resample_sr, rms_mix_rate, protect, output_format="wav"):
    if not input_audio:
        return None, "Please upload an audio file!"

    device = "cuda" if torch.cuda.is_available() else "cpu"

    model_path = os.path.join("inputs", "audio", "rvc_models", model_folder)

    try:
        pth_files = [f for f in os.listdir(model_path) if f.endswith('.pth')]
        if not pth_files:
            return None, f"No .pth file found in the selected model folder: {model_folder}"

        model_file = os.path.join(model_path, pth_files[0])

        rvc = RVCInference(device=device)
        rvc.load_model(model_file)
        rvc.set_params(f0method=f0method, f0up_key=f0up_key, index_rate=index_rate, filter_radius=filter_radius, resample_sr=resample_sr, rms_mix_rate=rms_mix_rate, protect=protect)

        today = datetime.now().date()
        output_dir = os.path.join('outputs', f"RVC_{today.strftime('%Y%m%d')}")
        os.makedirs(output_dir, exist_ok=True)

        output_filename = f"rvc_output_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{output_format}"
        output_path = os.path.join(output_dir, output_filename)

        rvc.infer_file(input_audio, output_path)

        rvc.unload_model()

        return output_path, None

    finally:
        if 'rvc' in locals():
            del rvc
        flush()
        
And my code for Command Line Interface:

python -m rvc_python cli -i C:\Users\dartv\Downloads\1.wav -o output.wav -mp inputs/audio/rvc_models/oxxxymiron/Oxxxymiron.pth -de cuda:0

or

python -m rvc_python cli -i C:\Users\dartv\Downloads\1.wav -o output.wav -md inputs/audio/rvc_models/oxxxymiron/ -mp Oxxxymiron.pth -de cuda:0

What could be the problem and how to fix it? I will be very grateful for help.

P.S. I use python 3.10.11 on windows 11

**Comment by wirytiox** [comment]
i am having a similar issue here. python 3.10.11 and win 11. 
using:` C:\Users\juanj\Desktop\blyat\rvc-python\venv\Scripts\python.exe -m rvc_python api -de cuda:0 -p 5050 -l -pm "Rie Takahashi (Japanese) 1347 Epoch"`
instead of: `C:\Users\juanj\Desktop\blyat\rvc-python\venv\Scripts\python.exe -m rvc_python api -de cuda:0 -p 5050 -l -pm "rvc_models\Rie Takahashi (Japanese) 1347 Epoch\G_1347.pth"`
got me to a different error:
```(venv) PS C:\Users\juanj\Desktop\blyat\rvc-python> C:\Users\juanj\Desktop\blyat\rvc-python\venv\Scripts\python.exe -m rvc_python api -de cuda:0 -p 5050 -l -pm "Rie Takahashi (Japanese) 1347 Epoch"
2024-09-12 09:55:52 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-09-12 09:55:53 | INFO | rvc_python.configs.config | Found GPU NVIDIA GeForce RTX 3050
is_half:True, device:cuda:0
2024-09-12 09:55:53 | INFO | rvc_python.modules.vc.modules | Loading: rvc_models\Rie Takahashi (Japanese) 1347 Epoch\G_1347.pth
Traceback (most recent call last):
  File "C:\Users\juanj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\juanj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\juanj\Desktop\blyat\rvc-python\rvc_python\__main__.py", line 91, in <module>
    main()
  File "C:\Users\juanj\Desktop\blyat\rvc-python\rvc_python\__main__.py", line 77, in main
    rvc.load_model(args.preload_model)
  File "C:\Users\juanj\Desktop\blyat\rvc-python\rvc_python\infer.py", line 62, in load_model
    self.vc.get_vc(model_path, version)
  File "C:\Users\juanj\Desktop\blyat\rvc-python\rvc_python\modules\vc\modules.py", line 104, in get_vc
    self.tgt_sr = self.cpt["config"][-1]
KeyError: 'config'

**Comment by Alexhal9000** [comment]
It is because they haven't updated the documentation, the code assumes you have a folder with a name structure rvc_models/name_of_model/name_of_model.pth, thus rvc.load_model("name_of_model") ; not the path

**Comment by daswer123** [comment]
[#](https://github.com/daswer123/rvc-python/issues/33#issuecomment-2454491056)
