### ISSUE TITLE
Cli client is not finding the model

### ISSUE THREAD

**Issue by c2v4** [daswer123/rvc-python#33]
Hi I've tried to execute what is written in the documentation. I am getting an error that the model could not be found.

```bash
❯ python -m rvc_python cli -i hello.mp3 -o hello-imp.mp3 -mp git/rvc-tts-webui/weights/Narrator-TSP/Narrator-TSP_278e.pth
2024-10-24 14:20:31 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-10-24 14:20:32 | INFO | rvc_python.configs.config | Found GPU NVIDIA GeForce RTX 4070 Ti
is_half:True, device:cpu:0
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/c2v4/.local/lib/python3.10/site-packages/rvc_python/__main__.py", line 91, in <module>
    main()
  File "/home/c2v4/.local/lib/python3.10/site-packages/rvc_python/__main__.py", line 57, in main
    rvc.load_model(args.model)
  File "/home/c2v4/.local/lib/python3.10/site-packages/rvc_python/infer.py", line 59, in load_model
    raise ValueError(f"Model {model_name} not found.")
ValueError: Model git/rvc-tts-webui/weights/Narrator-TSP/Narrator-TSP_278e.pth not found.
❯ ls git/rvc-tts-webui/weights/Narrator-TSP/Narrator-TSP_278e.pth
git/rvc-tts-webui/weights/Narrator-TSP/Narrator-TSP_278e.pth
```
The file is obviously there, available to be picked

**Comment by pentecoste** [comment]
Had your same problem, it's because the documentation is not correct. [This](https://github.com/daswer123/rvc-python/issues/24#issuecomment-2360020893) was the solution for me.

**Comment by daswer123** [comment]
Sorry, I fixed it and forgot to upload version 0.1.5 to pypi so it looks like the code on the github was fixed and you used the old version.

I've updated the version, it should work now
